trigger:
  batch: "true"
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    version: '8.0.x'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'costin-zaharia-sonarsource'
    scannerMode: 'MSBuild'
    projectKey: 'costin-zaharia-sonarsource_SimplePipelineAnalyzedProject'
    projectName: 'Simple [testing]'
    extraProperties: 
      sonar.verbose=true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
